apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-system-node-agent
spec:
  selector:
    matchLabels:
      app: system-node-agent
  template:
    metadata:
      labels:
        app: system-node-agent
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - system
      containers:
        - name: node-agent
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              while true; do
                echo "system daemon running on $(hostname)";
                sleep 30;
              done